bdtr.o: bdtr.cc mconf.h protos.h
btdtr.o: btdtr.cc mconf.h protos.h
chdtr.o: chdtr.cc mconf.h protos.h
const.o: const.cc mconf.h protos.h
drand.o: drand.cc mconf.h protos.h
fdtr.o: fdtr.cc mconf.h protos.h
gamma.o: gamma.cc mconf.h protos.h
gdtr.o: gdtr.cc mconf.h protos.h
igam.o: igam.cc mconf.h protos.h
igami.o: igami.cc mconf.h protos.h
incbet.o: incbet.cc mconf.h protos.h
incbi.o: incbi.cc mconf.h protos.h
mtherr.o: mtherr.cc mconf.h protos.h
nbdtr.o: nbdtr.cc mconf.h protos.h
ndtr.o: ndtr.cc mconf.h protos.h
ndtri.o: ndtri.cc mconf.h protos.h
pdtr.o: pdtr.cc mconf.h protos.h
polevl.o: polevl.cc mconf.h protos.h
stdtr.o: stdtr.cc mconf.h protos.h
unity.o: unity.cc mconf.h protos.h
