filter.o: filter.cpp filter.h ../include/imagecore.h \
 ../include/../imagebase/image.h ../include/../imagebase/imagebase.h \
 ../include/mydefine.h ../include/../imagebase/pixfmt.h \
 ../include/../imagebase/rgbpixels.h ../include/common.h \
 ../include/../common/commfunc.h ../include/../common/point.h \
 ../include/../imagebase/bitmap.h ../include/../imagebase/palette.h \
 ../include/../imagebase/iterator.h \
 ../include/../imagebase/../math/mathcommon.h \
 ../include/../imagebase/../math/matrix.h \
 ../include/../imagebase/../math/vector.h \
 ../include/../imagebase/../math/vectorD.h \
 ../include/../imagebase/../math/iterator.h \
 ../include/../imagebase/../math/matrix2D.h \
 ../include/../imagebase/../math/matrix3D.h \
 ../include/../imagebase/../math/matrix4D.h \
 ../include/../imagebase/imagehelper.h ../include/zmath.h \
 ../include/../math/mathcommon.h ../include/../math/eigensystem.h \
 ../include/../math/vector.h ../include/../math/matrix.h \
 ../include/../math/quaternion.h ../include/../math/svd.h
imalgorithm.o: imalgorithm.cpp ../include/mydefine.h \
 ../include/common.h ../include/../common/commfunc.h \
 ../include/../common/point.h landmark.h ../include/zmath.h \
 ../include/../math/mathcommon.h ../include/../math/matrix.h \
 ../include/../math/vector.h ../include/../math/vectorD.h \
 ../include/../math/iterator.h ../include/../math/matrix2D.h \
 ../include/../math/matrix3D.h ../include/../math/matrix4D.h \
 ../include/../math/eigensystem.h ../include/../math/quaternion.h \
 ../include/../math/svd.h imalgorithm.h ../include/imagecore.h \
 ../include/../imagebase/image.h ../include/../imagebase/imagebase.h \
 ../include/../imagebase/pixfmt.h ../include/../imagebase/rgbpixels.h \
 ../include/../imagebase/bitmap.h ../include/../imagebase/palette.h \
 ../include/../imagebase/iterator.h \
 ../include/../imagebase/../math/mathcommon.h \
 ../include/../imagebase/imagehelper.h filter.h
imdraw.o: imdraw.cpp ../include/common.h \
 ../include/../common/commfunc.h ../include/mydefine.h \
 ../include/../common/point.h imdraw.h ../include/imagecore.h \
 ../include/../imagebase/image.h ../include/../imagebase/imagebase.h \
 ../include/../imagebase/pixfmt.h ../include/../imagebase/rgbpixels.h \
 ../include/../imagebase/bitmap.h ../include/../imagebase/palette.h \
 ../include/../imagebase/iterator.h \
 ../include/../imagebase/../math/mathcommon.h \
 ../include/../imagebase/../math/matrix.h \
 ../include/../imagebase/../math/vector.h \
 ../include/../imagebase/../math/vectorD.h \
 ../include/../imagebase/../math/iterator.h \
 ../include/../imagebase/../math/matrix2D.h \
 ../include/../imagebase/../math/matrix3D.h \
 ../include/../imagebase/../math/matrix4D.h \
 ../include/../imagebase/imagehelper.h ../include/zmath.h \
 ../include/../math/mathcommon.h ../include/../math/eigensystem.h \
 ../include/../math/vector.h ../include/../math/matrix.h \
 ../include/../math/quaternion.h ../include/../math/svd.h landmark.h \
 filter.h
kmean.o: kmean.cpp kmean.h ../include/imagecore.h \
 ../include/../imagebase/image.h ../include/../imagebase/imagebase.h \
 ../include/mydefine.h ../include/../imagebase/pixfmt.h \
 ../include/../imagebase/rgbpixels.h ../include/common.h \
 ../include/../common/commfunc.h ../include/../common/point.h \
 ../include/../imagebase/bitmap.h ../include/../imagebase/palette.h \
 ../include/../imagebase/iterator.h \
 ../include/../imagebase/../math/mathcommon.h \
 ../include/../imagebase/../math/matrix.h \
 ../include/../imagebase/../math/vector.h \
 ../include/../imagebase/../math/vectorD.h \
 ../include/../imagebase/../math/iterator.h \
 ../include/../imagebase/../math/matrix2D.h \
 ../include/../imagebase/../math/matrix3D.h \
 ../include/../imagebase/../math/matrix4D.h \
 ../include/../imagebase/imagehelper.h
landmark.o: landmark.cpp landmark.h ../include/mydefine.h \
 ../include/common.h ../include/../common/commfunc.h \
 ../include/../common/point.h ../include/zmath.h \
 ../include/../math/mathcommon.h ../include/../math/matrix.h \
 ../include/../math/vector.h ../include/../math/vectorD.h \
 ../include/../math/iterator.h ../include/../math/matrix2D.h \
 ../include/../math/matrix3D.h ../include/../math/matrix4D.h \
 ../include/../math/eigensystem.h ../include/../math/quaternion.h \
 ../include/../math/svd.h
morphology.o: morphology.cpp morphology.h ../include/imagecore.h \
 ../include/../imagebase/image.h ../include/../imagebase/imagebase.h \
 ../include/mydefine.h ../include/../imagebase/pixfmt.h \
 ../include/../imagebase/rgbpixels.h ../include/common.h \
 ../include/../common/commfunc.h ../include/../common/point.h \
 ../include/../imagebase/bitmap.h ../include/../imagebase/palette.h \
 ../include/../imagebase/iterator.h \
 ../include/../imagebase/../math/mathcommon.h \
 ../include/../imagebase/../math/matrix.h \
 ../include/../imagebase/../math/vector.h \
 ../include/../imagebase/../math/vectorD.h \
 ../include/../imagebase/../math/iterator.h \
 ../include/../imagebase/../math/matrix2D.h \
 ../include/../imagebase/../math/matrix3D.h \
 ../include/../imagebase/../math/matrix4D.h \
 ../include/../imagebase/imagehelper.h ../include/zmath.h \
 ../include/../math/mathcommon.h ../include/../math/eigensystem.h \
 ../include/../math/vector.h ../include/../math/matrix.h \
 ../include/../math/quaternion.h ../include/../math/svd.h
parameter.o: parameter.cpp parameter.h ../include/imagecore.h \
 ../include/../imagebase/image.h ../include/../imagebase/imagebase.h \
 ../include/mydefine.h ../include/../imagebase/pixfmt.h \
 ../include/../imagebase/rgbpixels.h ../include/common.h \
 ../include/../common/commfunc.h ../include/../common/point.h \
 ../include/../imagebase/bitmap.h ../include/../imagebase/palette.h \
 ../include/../imagebase/iterator.h \
 ../include/../imagebase/../math/mathcommon.h \
 ../include/../imagebase/../math/matrix.h \
 ../include/../imagebase/../math/vector.h \
 ../include/../imagebase/../math/vectorD.h \
 ../include/../imagebase/../math/iterator.h \
 ../include/../imagebase/../math/matrix2D.h \
 ../include/../imagebase/../math/matrix3D.h \
 ../include/../imagebase/../math/matrix4D.h \
 ../include/../imagebase/imagehelper.h thresholding.h \
 ../include/zmath.h ../include/../math/mathcommon.h \
 ../include/../math/eigensystem.h ../include/../math/vector.h \
 ../include/../math/matrix.h ../include/../math/quaternion.h \
 ../include/../math/svd.h kmean.h
region.o: region.cpp region.h ../include/imagecore.h \
 ../include/../imagebase/image.h ../include/../imagebase/imagebase.h \
 ../include/mydefine.h ../include/../imagebase/pixfmt.h \
 ../include/../imagebase/rgbpixels.h ../include/common.h \
 ../include/../common/commfunc.h ../include/../common/point.h \
 ../include/../imagebase/bitmap.h ../include/../imagebase/palette.h \
 ../include/../imagebase/iterator.h \
 ../include/../imagebase/../math/mathcommon.h \
 ../include/../imagebase/../math/matrix.h \
 ../include/../imagebase/../math/vector.h \
 ../include/../imagebase/../math/vectorD.h \
 ../include/../imagebase/../math/iterator.h \
 ../include/../imagebase/../math/matrix2D.h \
 ../include/../imagebase/../math/matrix3D.h \
 ../include/../imagebase/../math/matrix4D.h \
 ../include/../imagebase/imagehelper.h ../include/zmath.h \
 ../include/../math/mathcommon.h ../include/../math/eigensystem.h \
 ../include/../math/vector.h ../include/../math/matrix.h \
 ../include/../math/quaternion.h ../include/../math/svd.h \
 ../include/imageio.h ../include/../imageio/imagereader.h \
 imalgorithm.h landmark.h filter.h
thresholding.o: thresholding.cpp thresholding.h ../include/imagecore.h \
 ../include/../imagebase/image.h ../include/../imagebase/imagebase.h \
 ../include/mydefine.h ../include/../imagebase/pixfmt.h \
 ../include/../imagebase/rgbpixels.h ../include/common.h \
 ../include/../common/commfunc.h ../include/../common/point.h \
 ../include/../imagebase/bitmap.h ../include/../imagebase/palette.h \
 ../include/../imagebase/iterator.h \
 ../include/../imagebase/../math/mathcommon.h \
 ../include/../imagebase/../math/matrix.h \
 ../include/../imagebase/../math/vector.h \
 ../include/../imagebase/../math/vectorD.h \
 ../include/../imagebase/../math/iterator.h \
 ../include/../imagebase/../math/matrix2D.h \
 ../include/../imagebase/../math/matrix3D.h \
 ../include/../imagebase/../math/matrix4D.h \
 ../include/../imagebase/imagehelper.h ../include/zmath.h \
 ../include/../math/mathcommon.h ../include/../math/eigensystem.h \
 ../include/../math/vector.h ../include/../math/matrix.h \
 ../include/../math/quaternion.h ../include/../math/svd.h
vectorkmean.o: vectorkmean.cpp vectorkmean.h ../include/zmath.h \
 ../include/../math/mathcommon.h ../include/../math/matrix.h \
 ../include/../math/vector.h ../include/mydefine.h \
 ../include/../math/vectorD.h ../include/common.h \
 ../include/../common/commfunc.h ../include/../common/point.h \
 ../include/../math/iterator.h ../include/../math/matrix2D.h \
 ../include/../math/matrix3D.h ../include/../math/matrix4D.h \
 ../include/../math/eigensystem.h ../include/../math/quaternion.h \
 ../include/../math/svd.h ../include/imagecore.h \
 ../include/../imagebase/image.h ../include/../imagebase/imagebase.h \
 ../include/../imagebase/pixfmt.h ../include/../imagebase/rgbpixels.h \
 ../include/../imagebase/bitmap.h ../include/../imagebase/palette.h \
 ../include/../imagebase/iterator.h \
 ../include/../imagebase/../math/mathcommon.h \
 ../include/../imagebase/imagehelper.h ../datastruct/tree.h
