fileavw.o: fileavw.cpp fileavw.h format.h \
  /usr/local/fsl/include/zimage/imagecore.h \
  /usr/local/fsl/include/zimage/image.h \
  /usr/local/fsl/include/zimage/imagebase.h \
  /usr/local/fsl/include/zimage/mydefine.h \
  /usr/local/fsl/include/zimage/pixfmt.h \
  /usr/local/fsl/include/zimage/rgbpixels.h \
  /usr/local/fsl/include/zimage/common.h \
  /usr/local/fsl/include/zimage/commfunc.h \
  /usr/local/fsl/include/zimage/handler.h \
  /usr/local/fsl/include/zimage/mstring.h \
  /usr/local/fsl/include/zimage/operator.h \
  /usr/local/fsl/include/zimage/point.h \
  /usr/local/fsl/include/zimage/random.h \
  /usr/local/fsl/include/zimage/bitmap.h \
  /usr/local/fsl/include/zimage/palette.h \
  /usr/local/fsl/include/zimage/imageiter.h \
  /usr/local/fsl/include/zimage/imagehelper.h imagereader.h
filebmp.o: filebmp.cpp filebmp.h format.h \
  /usr/local/fsl/include/zimage/imagecore.h \
  /usr/local/fsl/include/zimage/image.h \
  /usr/local/fsl/include/zimage/imagebase.h \
  /usr/local/fsl/include/zimage/mydefine.h \
  /usr/local/fsl/include/zimage/pixfmt.h \
  /usr/local/fsl/include/zimage/rgbpixels.h \
  /usr/local/fsl/include/zimage/common.h \
  /usr/local/fsl/include/zimage/commfunc.h \
  /usr/local/fsl/include/zimage/handler.h \
  /usr/local/fsl/include/zimage/mstring.h \
  /usr/local/fsl/include/zimage/operator.h \
  /usr/local/fsl/include/zimage/point.h \
  /usr/local/fsl/include/zimage/random.h \
  /usr/local/fsl/include/zimage/bitmap.h \
  /usr/local/fsl/include/zimage/palette.h \
  /usr/local/fsl/include/zimage/imageiter.h \
  /usr/local/fsl/include/zimage/imagehelper.h imagereader.h
filepgm.o: filepgm.cpp filepgm.h format.h \
  /usr/local/fsl/include/zimage/imagecore.h \
  /usr/local/fsl/include/zimage/image.h \
  /usr/local/fsl/include/zimage/imagebase.h \
  /usr/local/fsl/include/zimage/mydefine.h \
  /usr/local/fsl/include/zimage/pixfmt.h \
  /usr/local/fsl/include/zimage/rgbpixels.h \
  /usr/local/fsl/include/zimage/common.h \
  /usr/local/fsl/include/zimage/commfunc.h \
  /usr/local/fsl/include/zimage/handler.h \
  /usr/local/fsl/include/zimage/mstring.h \
  /usr/local/fsl/include/zimage/operator.h \
  /usr/local/fsl/include/zimage/point.h \
  /usr/local/fsl/include/zimage/random.h \
  /usr/local/fsl/include/zimage/bitmap.h \
  /usr/local/fsl/include/zimage/palette.h \
  /usr/local/fsl/include/zimage/imageiter.h \
  /usr/local/fsl/include/zimage/imagehelper.h imagereader.h
fileps.o: fileps.cpp fileps.h filehandle.h format.h \
  /usr/local/fsl/include/zimage/imagecore.h \
  /usr/local/fsl/include/zimage/image.h \
  /usr/local/fsl/include/zimage/imagebase.h \
  /usr/local/fsl/include/zimage/mydefine.h \
  /usr/local/fsl/include/zimage/pixfmt.h \
  /usr/local/fsl/include/zimage/rgbpixels.h \
  /usr/local/fsl/include/zimage/common.h \
  /usr/local/fsl/include/zimage/commfunc.h \
  /usr/local/fsl/include/zimage/handler.h \
  /usr/local/fsl/include/zimage/mstring.h \
  /usr/local/fsl/include/zimage/operator.h \
  /usr/local/fsl/include/zimage/point.h \
  /usr/local/fsl/include/zimage/random.h \
  /usr/local/fsl/include/zimage/bitmap.h \
  /usr/local/fsl/include/zimage/palette.h \
  /usr/local/fsl/include/zimage/imageiter.h \
  /usr/local/fsl/include/zimage/imagehelper.h imagereader.h
imageiocommon.o: imageiocommon.cpp \
  /usr/local/fsl/include/zimage/imagecore.h \
  /usr/local/fsl/include/zimage/image.h \
  /usr/local/fsl/include/zimage/imagebase.h \
  /usr/local/fsl/include/zimage/mydefine.h \
  /usr/local/fsl/include/zimage/pixfmt.h \
  /usr/local/fsl/include/zimage/rgbpixels.h \
  /usr/local/fsl/include/zimage/common.h \
  /usr/local/fsl/include/zimage/commfunc.h \
  /usr/local/fsl/include/zimage/handler.h \
  /usr/local/fsl/include/zimage/mstring.h \
  /usr/local/fsl/include/zimage/operator.h \
  /usr/local/fsl/include/zimage/point.h \
  /usr/local/fsl/include/zimage/random.h \
  /usr/local/fsl/include/zimage/bitmap.h \
  /usr/local/fsl/include/zimage/palette.h \
  /usr/local/fsl/include/zimage/imageiter.h \
  /usr/local/fsl/include/zimage/imagehelper.h
imagereader.o: imagereader.cpp imagereader.h \
  /usr/local/fsl/include/zimage/imagecore.h \
  /usr/local/fsl/include/zimage/image.h \
  /usr/local/fsl/include/zimage/imagebase.h \
  /usr/local/fsl/include/zimage/mydefine.h \
  /usr/local/fsl/include/zimage/pixfmt.h \
  /usr/local/fsl/include/zimage/rgbpixels.h \
  /usr/local/fsl/include/zimage/common.h \
  /usr/local/fsl/include/zimage/commfunc.h \
  /usr/local/fsl/include/zimage/handler.h \
  /usr/local/fsl/include/zimage/mstring.h \
  /usr/local/fsl/include/zimage/operator.h \
  /usr/local/fsl/include/zimage/point.h \
  /usr/local/fsl/include/zimage/random.h \
  /usr/local/fsl/include/zimage/bitmap.h \
  /usr/local/fsl/include/zimage/palette.h \
  /usr/local/fsl/include/zimage/imageiter.h \
  /usr/local/fsl/include/zimage/imagehelper.h filepgm.h format.h \
  filebmp.h fileavw.h fileps.h filehandle.h
