fileavw.o: fileavw.cpp fileavw.h format.h ../include/imagecore.h \
 ../include/../imagebase/image.h ../include/../imagebase/imagebase.h \
 ../include/mydefine.h ../include/../imagebase/pixfmt.h \
 ../include/../imagebase/rgbpixels.h ../include/common.h \
 ../include/../common/commfunc.h ../include/../common/point.h \
 ../include/../imagebase/bitmap.h ../include/../imagebase/palette.h \
 ../include/../imagebase/iterator.h \
 ../include/../imagebase/../math/mathcommon.h \
 ../include/../imagebase/../math/matrix.h \
 ../include/../imagebase/../math/vector.h \
 ../include/../imagebase/../math/vectorD.h \
 ../include/../imagebase/../math/iterator.h \
 ../include/../imagebase/../math/matrix2D.h \
 ../include/../imagebase/../math/matrix3D.h \
 ../include/../imagebase/../math/matrix4D.h \
 ../include/../imagebase/imagehelper.h imagereader.h
filebmp.o: filebmp.cpp filebmp.h format.h ../include/imagecore.h \
 ../include/../imagebase/image.h ../include/../imagebase/imagebase.h \
 ../include/mydefine.h ../include/../imagebase/pixfmt.h \
 ../include/../imagebase/rgbpixels.h ../include/common.h \
 ../include/../common/commfunc.h ../include/../common/point.h \
 ../include/../imagebase/bitmap.h ../include/../imagebase/palette.h \
 ../include/../imagebase/iterator.h \
 ../include/../imagebase/../math/mathcommon.h \
 ../include/../imagebase/../math/matrix.h \
 ../include/../imagebase/../math/vector.h \
 ../include/../imagebase/../math/vectorD.h \
 ../include/../imagebase/../math/iterator.h \
 ../include/../imagebase/../math/matrix2D.h \
 ../include/../imagebase/../math/matrix3D.h \
 ../include/../imagebase/../math/matrix4D.h \
 ../include/../imagebase/imagehelper.h imagereader.h
filegif.o: filegif.cpp filegif.h format.h ../include/imagecore.h \
 ../include/../imagebase/image.h ../include/../imagebase/imagebase.h \
 ../include/mydefine.h ../include/../imagebase/pixfmt.h \
 ../include/../imagebase/rgbpixels.h ../include/common.h \
 ../include/../common/commfunc.h ../include/../common/point.h \
 ../include/../imagebase/bitmap.h ../include/../imagebase/palette.h \
 ../include/../imagebase/iterator.h \
 ../include/../imagebase/../math/mathcommon.h \
 ../include/../imagebase/../math/matrix.h \
 ../include/../imagebase/../math/vector.h \
 ../include/../imagebase/../math/vectorD.h \
 ../include/../imagebase/../math/iterator.h \
 ../include/../imagebase/../math/matrix2D.h \
 ../include/../imagebase/../math/matrix3D.h \
 ../include/../imagebase/../math/matrix4D.h \
 ../include/../imagebase/imagehelper.h imagereader.h
filejpg.o: filejpg.cpp filejpg.h filehandle.h format.h \
 ../include/imagecore.h ../include/../imagebase/image.h \
 ../include/../imagebase/imagebase.h ../include/mydefine.h \
 ../include/../imagebase/pixfmt.h ../include/../imagebase/rgbpixels.h \
 ../include/common.h ../include/../common/commfunc.h \
 ../include/../common/point.h ../include/../imagebase/bitmap.h \
 ../include/../imagebase/palette.h ../include/../imagebase/iterator.h \
 ../include/../imagebase/../math/mathcommon.h \
 ../include/../imagebase/../math/matrix.h \
 ../include/../imagebase/../math/vector.h \
 ../include/../imagebase/../math/vectorD.h \
 ../include/../imagebase/../math/iterator.h \
 ../include/../imagebase/../math/matrix2D.h \
 ../include/../imagebase/../math/matrix3D.h \
 ../include/../imagebase/../math/matrix4D.h \
 ../include/../imagebase/imagehelper.h imagereader.h \
 ../external/jpeg/jpeglib.h ../external/jpeg/jconfig.h \
 ../external/jpeg/jmorecfg.h
filemit.o: filemit.cpp filemit.h format.h ../include/imagecore.h \
 ../include/../imagebase/image.h ../include/../imagebase/imagebase.h \
 ../include/mydefine.h ../include/../imagebase/pixfmt.h \
 ../include/../imagebase/rgbpixels.h ../include/common.h \
 ../include/../common/commfunc.h ../include/../common/point.h \
 ../include/../imagebase/bitmap.h ../include/../imagebase/palette.h \
 ../include/../imagebase/iterator.h \
 ../include/../imagebase/../math/mathcommon.h \
 ../include/../imagebase/../math/matrix.h \
 ../include/../imagebase/../math/vector.h \
 ../include/../imagebase/../math/vectorD.h \
 ../include/../imagebase/../math/iterator.h \
 ../include/../imagebase/../math/matrix2D.h \
 ../include/../imagebase/../math/matrix3D.h \
 ../include/../imagebase/../math/matrix4D.h \
 ../include/../imagebase/imagehelper.h imagereader.h
filepgm.o: filepgm.cpp filepgm.h format.h ../include/imagecore.h \
 ../include/../imagebase/image.h ../include/../imagebase/imagebase.h \
 ../include/mydefine.h ../include/../imagebase/pixfmt.h \
 ../include/../imagebase/rgbpixels.h ../include/common.h \
 ../include/../common/commfunc.h ../include/../common/point.h \
 ../include/../imagebase/bitmap.h ../include/../imagebase/palette.h \
 ../include/../imagebase/iterator.h \
 ../include/../imagebase/../math/mathcommon.h \
 ../include/../imagebase/../math/matrix.h \
 ../include/../imagebase/../math/vector.h \
 ../include/../imagebase/../math/vectorD.h \
 ../include/../imagebase/../math/iterator.h \
 ../include/../imagebase/../math/matrix2D.h \
 ../include/../imagebase/../math/matrix3D.h \
 ../include/../imagebase/../math/matrix4D.h \
 ../include/../imagebase/imagehelper.h imagereader.h
filepng.o: filepng.cpp filepng.h filehandle.h format.h \
 ../include/imagecore.h ../include/../imagebase/image.h \
 ../include/../imagebase/imagebase.h ../include/mydefine.h \
 ../include/../imagebase/pixfmt.h ../include/../imagebase/rgbpixels.h \
 ../include/common.h ../include/../common/commfunc.h \
 ../include/../common/point.h ../include/../imagebase/bitmap.h \
 ../include/../imagebase/palette.h ../include/../imagebase/iterator.h \
 ../include/../imagebase/../math/mathcommon.h \
 ../include/../imagebase/../math/matrix.h \
 ../include/../imagebase/../math/vector.h \
 ../include/../imagebase/../math/vectorD.h \
 ../include/../imagebase/../math/iterator.h \
 ../include/../imagebase/../math/matrix2D.h \
 ../include/../imagebase/../math/matrix3D.h \
 ../include/../imagebase/../math/matrix4D.h \
 ../include/../imagebase/imagehelper.h imagereader.h \
 ../external/png/png.h ../external/png/../zlib/zlib.h \
 ../external/png/../zlib/zconf.h ../external/png/pngconf.h
fileps.o: fileps.cpp fileps.h filehandle.h format.h \
 ../include/imagecore.h ../include/../imagebase/image.h \
 ../include/../imagebase/imagebase.h ../include/mydefine.h \
 ../include/../imagebase/pixfmt.h ../include/../imagebase/rgbpixels.h \
 ../include/common.h ../include/../common/commfunc.h \
 ../include/../common/point.h ../include/../imagebase/bitmap.h \
 ../include/../imagebase/palette.h ../include/../imagebase/iterator.h \
 ../include/../imagebase/../math/mathcommon.h \
 ../include/../imagebase/../math/matrix.h \
 ../include/../imagebase/../math/vector.h \
 ../include/../imagebase/../math/vectorD.h \
 ../include/../imagebase/../math/iterator.h \
 ../include/../imagebase/../math/matrix2D.h \
 ../include/../imagebase/../math/matrix3D.h \
 ../include/../imagebase/../math/matrix4D.h \
 ../include/../imagebase/imagehelper.h imagereader.h
filetif.o: filetif.cpp ../external/tiff/tiffio.h \
 ../external/tiff/tiff.h filetif.h filehandle.h format.h \
 ../include/imagecore.h ../include/../imagebase/image.h \
 ../include/../imagebase/imagebase.h ../include/mydefine.h \
 ../include/../imagebase/pixfmt.h ../include/../imagebase/rgbpixels.h \
 ../include/common.h ../include/../common/commfunc.h \
 ../include/../common/point.h ../include/../imagebase/bitmap.h \
 ../include/../imagebase/palette.h ../include/../imagebase/iterator.h \
 ../include/../imagebase/../math/mathcommon.h \
 ../include/../imagebase/../math/matrix.h \
 ../include/../imagebase/../math/vector.h \
 ../include/../imagebase/../math/vectorD.h \
 ../include/../imagebase/../math/iterator.h \
 ../include/../imagebase/../math/matrix2D.h \
 ../include/../imagebase/../math/matrix3D.h \
 ../include/../imagebase/../math/matrix4D.h \
 ../include/../imagebase/imagehelper.h imagereader.h
filetxt.o: filetxt.cpp filetxt.h format.h ../include/imagecore.h \
 ../include/../imagebase/image.h ../include/../imagebase/imagebase.h \
 ../include/mydefine.h ../include/../imagebase/pixfmt.h \
 ../include/../imagebase/rgbpixels.h ../include/common.h \
 ../include/../common/commfunc.h ../include/../common/point.h \
 ../include/../imagebase/bitmap.h ../include/../imagebase/palette.h \
 ../include/../imagebase/iterator.h \
 ../include/../imagebase/../math/mathcommon.h \
 ../include/../imagebase/../math/matrix.h \
 ../include/../imagebase/../math/vector.h \
 ../include/../imagebase/../math/vectorD.h \
 ../include/../imagebase/../math/iterator.h \
 ../include/../imagebase/../math/matrix2D.h \
 ../include/../imagebase/../math/matrix3D.h \
 ../include/../imagebase/../math/matrix4D.h \
 ../include/../imagebase/imagehelper.h imagereader.h
imageiocommon.o: imageiocommon.cpp ../include/imagecore.h \
 ../include/../imagebase/image.h ../include/../imagebase/imagebase.h \
 ../include/mydefine.h ../include/../imagebase/pixfmt.h \
 ../include/../imagebase/rgbpixels.h ../include/common.h \
 ../include/../common/commfunc.h ../include/../common/point.h \
 ../include/../imagebase/bitmap.h ../include/../imagebase/palette.h \
 ../include/../imagebase/iterator.h \
 ../include/../imagebase/../math/mathcommon.h \
 ../include/../imagebase/../math/matrix.h \
 ../include/../imagebase/../math/vector.h \
 ../include/../imagebase/../math/vectorD.h \
 ../include/../imagebase/../math/iterator.h \
 ../include/../imagebase/../math/matrix2D.h \
 ../include/../imagebase/../math/matrix3D.h \
 ../include/../imagebase/../math/matrix4D.h \
 ../include/../imagebase/imagehelper.h
imagereader.o: imagereader.cpp imagereader.h ../include/imagecore.h \
 ../include/../imagebase/image.h ../include/../imagebase/imagebase.h \
 ../include/mydefine.h ../include/../imagebase/pixfmt.h \
 ../include/../imagebase/rgbpixels.h ../include/common.h \
 ../include/../common/commfunc.h ../include/../common/point.h \
 ../include/../imagebase/bitmap.h ../include/../imagebase/palette.h \
 ../include/../imagebase/iterator.h \
 ../include/../imagebase/../math/mathcommon.h \
 ../include/../imagebase/../math/matrix.h \
 ../include/../imagebase/../math/vector.h \
 ../include/../imagebase/../math/vectorD.h \
 ../include/../imagebase/../math/iterator.h \
 ../include/../imagebase/../math/matrix2D.h \
 ../include/../imagebase/../math/matrix3D.h \
 ../include/../imagebase/../math/matrix4D.h \
 ../include/../imagebase/imagehelper.h filepgm.h format.h filemit.h \
 filebmp.h filegif.h fileavw.h filetif.h filehandle.h filejpg.h \
 filepng.h fileps.h filetxt.h
